### ISSUE TITLE
Service is not being deleted

### ISSUE THREAD

**Issue by macejmic** [3scale/porta#20]
**What happened**:

Service is not being deleted since State Machine is not being used during the deletion. 

**What you expected to happen**:

Error report tells us where the deletion happens. 

/kind bug

**Comment by Martouta** [comment]
Bug fixed 😄 💪 [THREESCALE-1194 - Services marked as "deleted", but not actually getting deleted](https://issues.jboss.org/browse/THREESCALE-1194)
