### ISSUE TITLE
Kubernetes/Openshift Service Discovery

### ISSUE THREAD

**Issue by guicassolato** [3scale/porta#34]
**Is your feature request related to a problem? Please describe.**

Currently, whenever 3scale is deployed to a k8s/okd cluster where other services/APIs are being hosted and orchestrated, and one wants to manage such APIs on 3scale, one has to add them manually. 3scale could use the cluster API could in combination with https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/proposals/service-discovery.md (or some extension of it) to discover services running in the the same cluster and make those APIs easy to be imported into the API management system.

Jira issue: [THREESCALE-1363](https://issues.jboss.org/browse/THREESCALE-1363)

**Describe the solution you would like**

An idea would be having two options for the creation of an API in 3scale Admin Portal: "From Scratch" and "Discover". The "Discover" would query the underlying k8s/okd cluster and list the discoverable services; then the admin user would simply choose one of them and "Import". From that, API's private URL could be generated by 3scale (routing to the local endpoint of the service within the cluster), as well as the swagger/OAS specs imported as ActiveDocs.

**Describe alternatives you have considered**
A possible alternative to the UI-based service discovery described above could be using a 3scale daemon pod or other type of cluster watchers/hooks to automatically identify a "discoverable" service just deployed to the cluster and add its API to 3scale.

/kind feature

**Comment by guicassolato** [comment]
Depends on:
- https://github.com/3scale/porta/pull/3
- https://github.com/3scale/porta/pull/62

Implementation plan:
- [ ] Discovery (Base) - https://github.com/3scale/porta/pull/35
- [ ] Async notifications
- [ ] Update/resync
- [ ] RHSSO
- [ ] Configurability (Service Discovery namespace, cluster local host, OAS content-types, etc)
- [ ] API Docs endpoints - https://github.com/3scale/porta/pull/73

**Comment by Martouta** [comment]
Is this already finished, @guicassolato ? I suspect so, and in that case, we can close this issue 😄
