### ISSUE TITLE
[Documentation for developers needed] Getting webpack related tests working locally is not strightforward

### ISSUE THREAD

**Issue by Martouta** [3scale/porta#495]
Gui was getting the following in a functional test (locally):
```
ActionView::Template::Error:         ActionView::Template::Error: Webpacker can't find stats.js in /Users/guilherme.cassolato/Workspace/porta/public/packs-test/manifest.json. Possible causes:
        1. You want to set webpacker.yml value of compile to true for your environment
           unless you are using the `webpack -w` or the webpack-dev-server.
        2. webpack has not yet re-run to reflect updates.
        3. You have misconfigured Webpacker's config/webpacker.yml file.
        4. Your webpack configuration is not creating a manifest.
```

Hery replied:

> You need to compile assets or use `webpack -w` (edited) 
> but normally it should run by itself.
> for test, `compile: true` should be set
> well locally
> ok so jst run webpack-dev-server
> we do compile in the ci because it is faster
> but locally what you would need is either change the `compile: true` in the webpacker.yml
> OR launch webpack-dev-server

But this should be documented 😄

**Comment by guicassolato** [comment]
It turns out I was missing `stats.js`. Deleted `public/packs-test`, recompiled it manually and it worked.

**Comment by Martouta** [comment]
Cool, then nothing to do :smile: Thanks for the info :+1:
