### ISSUE TITLE
Upgrade rails to rails 5.0

### ISSUE THREAD

**Issue by hallelujah** [3scale/porta#5]
[The maintenance policy of Ruby on Rails](https://guides.rubyonrails.org/maintenance_policy.html#severe-security-issues) states that only severe security updates will be included in 4.2.x

The current series is 5.2.x
Lets upgrade!

**Comment by Martouta** [comment]
Issue migrated to [THREESCALE-1605 - Rails 5.x migration](https://issues.jboss.org/browse/THREESCALE-1605) and particularly to its subtask [THREESCALE-1606 - Upgrade Rails to 5.0](https://issues.jboss.org/browse/THREESCALE-1606)
