### ISSUE TITLE
make bundle fails with Authentication is required for gems.contribsys.com

### ISSUE THREAD

**Issue by johnpoth** [3scale/porta#513]
**What happened**:
$make bundle 
Authentication is required for gems.contribsys.com.
Please supply credentials for this source. You can do this by running:
 bundle config gems.contribsys.com username:password

**What you expected to happen**:

Are there credentials that can be used? If not is there any way to still build the project?

**How to reproduce it**:

> Help the project maintainers reproduce your issue, as minimally and precisely as possible, so you can make it easier for them to work on it. The more accurate the steps, the higher the chance that someone will be able to assist in your request. 

**Anything else we need to know?**:

**Environment**:
- 3scale version:
- Ruby version: 
- OS (e.g. from /etc/os-release):
- Deployment method (e.g. `docker-compose`, with linked `docker-compose.yml` file, or link to gist with openshift resources/templates, or application server info + deployment for native deployments):
- Any other useful info:

/kind bug

**Comment by gsaslis** [comment]
@johnpoth can you please confirm what folder you're running the `make bundle` command in?

please make sure you've pulled the latest `master` and are running this in the project root. 

any other context / info you can share, more than welcome!

**Comment by johnpoth** [comment]
Hi @gsaslis, thanks for the quick response!

I am running this from the root folder on branch 'master'. I've synched the repo yesterday so everything should be pretty recent.

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Bundler version 2.0.1

HTH

**Comment by gsaslis** [comment]
can you try just `bundle install` ? 

(the `bundle` make target is kind of unused at the moment, as it still relies on `Gemfile.prod` for which [I have an open issue for, to be moved out of this repo,](https://github.com/3scale/porta/issues/450) as it does require creds).

btw - not sure what your use case is, but you might find the below links useful: 
* [Installation instructions](https://github.com/3scale/porta/blob/master/INSTALL.md) for 3scale/porta
* Some quick notes to [deploy all of 3scale on minishift](https://gist.github.com/gsaslis/015e3aa6ff283b3c4caedd9bc64f0c39)

**Comment by johnpoth** [comment]
Hi @gsaslis, I'm trying to run a unit test :)

```
ruby -I test  test/unit/validators/uri_validator_test.rb 
/home/jpoth/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.9/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection': 'test' database is not configured. Available: [] (ActiveRecord::AdapterNotSpecified)
```

I was hoping to avoid spinning a docker container but it looks like it's the way to go. I'll try out 
```
make test-run
```

Thanks!
