### ISSUE TITLE
Private Base URL fails when URL contains a path

### ISSUE THREAD

**Issue by johnpoth** [3scale/porta#519]
**What happened**:
When setting the 'Private Base URL' to:
```http://spring-boot-camel-rest-3scale-jpoth.b542.starter-us-east-2a.openshiftapps.com:80/camel-rest-3scale```

in my Admin Portal , I get the error 'The accepted format is 'http(s)://address(:port)(/path)'. Removing the path from the URL solves the problem.

**What you expected to happen**:

As per the error message, Paths should be supported. This [commit](https://github.com/3scale/porta/commit/0dd883b9101fe2599615377c9e3269a576009b30) seems relevant although I can't see where proxy_private_base_path is set to false. Thanks!

**How to reproduce it**:

I [signed up](https://www.3scale.net/signup/) for a 90 day trial version. Thanks!

**Anything else we need to know?**:

**Environment**:
- 3scale version:
- Ruby version: 
- OS (e.g. from /etc/os-release):
- Deployment method (e.g. `docker-compose`, with linked `docker-compose.yml` file, or link to gist with openshift resources/templates, or application server info + deployment for native deployments):
- Any other useful info:

/kind bug

**Comment by hallelujah** [comment]
Hi @johnpoth 

Thanks for reporting this.
This is the repository for the upstream version. Though the SaaS version is based on this repository, the configurations are different.

For issues concerning the SaaS version, you can look if your issue has been referenced in https://issues.jboss.org/projects/THREESCALE/summary or contact the SaaS support.

## Explanation

The commit you referenced means that unless the configuration is enabled, path cannot be used in the URL.

It is set to `false` if there is no configuration for it `#missing_config`.
The base class is 
The configuration is `config/rolling_updates.yml`

Example: 

https://github.com/3scale/porta/blob/c865ad5db23bd45c12b2d6ee57b39eafcbb01890/config/examples/rolling_updates.yml

Each config defined in this file is defined as a Ruby class inheriting from

https://github.com/3scale/porta/blob/c865ad5db23bd45c12b2d6ee57b39eafcbb01890/app/lib/logic/rolling_updates.rb#L59

**Comment by johnpoth** [comment]
thanks @hallelujah for responding, that was my understanding as well. I will close this issue (maybe setting the default value to ```true``` makes sense though)

**Comment by hallelujah** [comment]
That will be decided by the product team for the SaaS version I guess.
