### ISSUE TITLE
Installation guide missing Redis requirement

### ISSUE THREAD

**Issue by josemigallas** [3scale/porta#55]
There should be some steps describing how to get Redis running and hooked up with Porta. For example it can be run in Docker container:
```
docker run -p 6379:6379 -d redis
```

**Comment by mikz** [comment]
I think we are using docker compose to handle all the dependencies. And there is redis service: 
https://github.com/3scale/porta/blob/66eee3ba217b249fe665ff65103ba280fa20bf11/docker-compose.yml#L33-L37

Maybe we just should add it there: https://github.com/3scale/porta/blob/66eee3ba217b249fe665ff65103ba280fa20bf11/docker-compose.test-mysql.yml#L27

**Comment by gsaslis** [comment]
@mikz so that would mean:
[ ] removing redis from inside the docker image,
[ ] deploying it as a separate docker container, 
[ ] change `localhost` URLs for connecting to docker.

...anything i'm missing ?

**Comment by mikz** [comment]
Yes, or do it the other way around.

1) change localhost to use ENV variables published by docker first and fallback to localhost
2) start all dependencies using docker compose
3) remove redis-server from the image

**Comment by josemigallas** [comment]
Well, the issue is precisely that this info (Brewfile, docker or any other option) is not described in INSTALL.md. It ought to be there for contributors and whoever interested in running Porta.

**Comment by Martouta** [comment]
Fixed by https://github.com/3scale/porta/pull/89 😄 👍
