### ISSUE TITLE
Login API to get Access Token from user password

### ISSUE THREAD

**Issue by eguzki** [3scale/porta#582]
**Scenario**
Using 3scale API, having tenant's admin user's credentials (user/pass), cannot use 3scale API because it is based on `access_token` or `provider_key`

**Solution**

Login endpoint in 3scale API

```
POST /admin/api/login
```

Returning some of expiring `session token` or owned `access_token` valid for 3scale API operations:

```json
{ 
  "user": {
  "id": "2445582860376",
  "account_id": "244558268289",
  "state": "active",
  "role": "admin",
  "username": "admin",
  "session_token": "64646464646",
  "extra_fields": {}
}
```

An alternative solution would be to enable `user/pass` credentials on `Personal Access Token" API to create `access_token` and use it in 3scale API

**Comment by mikz** [comment]
Login endpoint definitely should not create a Personal Access Token, as that is permanent action. 

Creating a session the same way the SSO endpoint does is more reasonable.

**Comment by mikz** [comment]
And I think we should consider this seriously. I don't know APIs that allow you to use username+password for access. You always have to get token out of band to use the API.

I'd like to hear about the use case first, why this is needed and why none of the alternatives works.

**Comment by eguzki** [comment]
In the end, you need access_token to create secret in OCP environment. The SSO token available from SSO endpoint does not allow you to get/create access_token for a given admin user.

**Comment by eguzki** [comment]
access_token will be used by Binding controller from [3scale operator](https://github.com/3scale/3scale-operator) to create/update/delete tenant entities (services, metrics, plans, mapping rules, etc...)

**Comment by eguzki** [comment]
The use case does not need anymore requested feature.

Thnx @mikz  for clarification

closing the issue
