### ISSUE TITLE
403 Forbidden Importing the list of available projects from Openshift.

### ISSUE THREAD

**Issue by juazugas** [3scale/porta#594]
**What happened**:

Accessing to the “new API” link from the Dashboard in the 3scale admin web, then selecting the radio “Import from Openshift” in the next form, the XHR request for “/p/admin/service_discovery/projects.json” get 403 Forbidden.

As it’s seen in the request headers, the Cookie identifying the session is not passed to the XHR Request. 

```
> GET /p/admin/service_discovery/projects.json HTTP/1.1
> Accept-Encoding: deflate, gzip
> Host: 3scale-admin.acmeregistry.example.com
> User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
> Accept: */*
> Accept-Language: en-US,en;q=0.5
> Referer: https://3scale-admin.acmeregistry.example.com/apiconfig/services/new
> Origin: https://3scale-admin.acmeregistry.example.com
> Connection: keep-alive
> 
< HTTP/1.1 403 Forbidden
```

After some rummaging over the issue, and check that everything is well configured (Doing the request in another tab retrieves the list of projects), I discovered that our firefox version (57.0) has predefined a default ‘omit’ for the default credentials values passed to the `window.fetch` function in javascript. 

It wasn’t until version 61 that was changed to ‘same-origin’ as the default value, as we can see in mozilla MDN (https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials), here is the revision changes (https://hg.mozilla.org/mozilla-central/rev/2d657d8dadf9) and the reported bug  (https://bugzilla.mozilla.org/show_bug.cgi?id=1394399).

First workaround, I tryed to update the browser, but as a requirement we are running a RHEL Linux 7.6 and the latest version of firefox allowed is 60.5.0 (https://access.redhat.com/downloads/content/firefox/60.5.0-2.el7/x86_64/fd431d51/package).

As a quick solution I would suggest :

```
app/assets/javascripts/provider/layout/provider.js
@@ -856,7 +856,7 @@
 
   function fetchData(url, type) {
     if ('fetch' in window) {
-      fetch(url)
+      fetch(url, {credentials:'same-origin'})
       .then(function(response) {
           return response.json();
       })
```

It turns out that this is the only place in the app that a request is made from a javascript function using the fetch function.

A safest approach will be use a polyfill or a substitute safer function as is recommended in whatwg (https://github.com/whatwg/fetch/pull/585#issuecomment-325912190).

> Short description of the issue you are facing, possibly including relevant log output that highlights your problem. (Please use [Gists](https://gist.github.com) for large logs).

**What you expected to happen**:

The logs from the container  ...

```
system-provider:log
[8bad0cc3-b2a7-40bb-8f8a-df224efae363] [3scale-admin.**.example.com] [172.17.0.1] Started GET "/p/admin/service_discovery/projects.json" for 172.17.0.1 at 2019-02-05 14:26:10 +0000
[8bad0cc3-b2a7-40bb-8f8a-df224efae363] [3scale-admin.**.example.com] [172.17.0.1] Processing by Provider::Admin::ServiceDiscovery::ClusterProjectsController#index as JSON
[8bad0cc3-b2a7-40bb-8f8a-df224efae363] [3scale-admin.**.example.com] [172.17.0.1] Handling Exception: You are not authorized to access this page. with status forbidden
[8bad0cc3-b2a7-40bb-8f8a-df224efae363] [3scale-admin.**.example.com] [172.17.0.1] Filter chain halted as :login_required rendered or redirected
[8bad0cc3-b2a7-40bb-8f8a-df224efae363] [3scale-admin.**.example.com] [172.17.0.1] Completed 403 Forbidden in 7ms (Views: 0.2ms | ActiveRecord: 1.7ms)
```

> Please describe here the behaviour you were expecting.

**How to reproduce it**:

Configure a Service to be discovered on Openshift, following the guidelines of (https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.4/html/service_discovery/service-discovery-configuration-procedure), in my case "Configuring without SSO".

Access with a Firefox version prior 61, or use the latest firefox supported by RHEL 7 (60.5.0). It will not share the credentials to the XHR request, then it will receive a 403 Forbidden to the request.

> Help the project maintainers reproduce your issue, as minimally and precisely as possible, so you can make it easier for them to work on it. The more accurate the steps, the higher the chance that someone will be able to assist in your request. 

**Anything else we need to know?**:

**Environment**:
- 3scale version: : Version 2.4.0
- Ruby version: 
- OS (e.g. from /etc/os-release): Firefox 60.5.0 on RHEL 7.6 
- Deployment method (e.g. `docker-compose`, with linked `docker-compose.yml` file, or link to gist with openshift resources/templates, or application server info + deployment for native deployments): amp-2.4.yml (https://github.com/3scale/3scale-amp-openshift-templates/blob/master/amp/amp.yml)
- Any other useful info:

/kind bug

**Comment by guicassolato** [comment]
Jira issue opened to track this: https://issues.jboss.org/browse/THREESCALE-2254

**Comment by damianpm** [comment]
@juazugas Sorry for the delay in giving a heads up.
We finally solved the issue, we have moved this file to webpack and incorporated the fetch polyfill. 
For more details, see https://github.com/3scale/porta/pull/750
Thanks for your help, it was very useful!
