### ISSUE TITLE
Expose API's name on provider.api_specs liquid drop

### ISSUE THREAD

**Issue by ataxexe** [3scale/porta#61]
**Is your feature request related to a problem? Please describe.**

I'm trying to make a dynamic menu for all API's registered on the Active Docs and for that I'm using the `provider.api_specs` Liquid Drop.

Turns out that this drop only contains the `url` and `system_name`, which prevents the menu item creation because I need the name on the menu.

The goal is to reduce the friction to expose the Active Docs on the Developer Portal.

**Describe the solution you would like**

The solution might be adding the method `name` on `ApiSpec` class (file `lib/developer_portal/lib/liquid/drops/api_spec.rb`)

**Describe alternatives you have considered**

I haven't considered any other alternatives yet. Will be glad to have some insights if possible.

Thank you so much!

/kind feature

**Comment by guicassolato** [comment]
Thanks for opening the issue, @ataxexe. Indeed currently we miss a relationship between `Service` (API) and `ApiDocs::Service`. We were planning to do that soon as feature requests like https://github.com/3scale/porta/pull/35 depend on it.

cc/ @thomasmaas
