### ISSUE TITLE
Service settings missing in service endpoint

### ISSUE THREAD

**Issue by eguzki** [3scale/porta#668]
Using service read endpoint
> GET  /admin/api/services/{id}.json

Some settings are missing:
* intentions_required
* buyers_manage_apps
* buyers_manage_keys
* referrer_filters_required
* custom_keys_enabled
* buyer_key_regenerate_enabled
* mandatory_app_key
* buyer_can_select_plan

* buyer_plan_change_permission_request
* buyer_plan_change_permission_direct
* service_buyer_plan_change_permission_credit_card
* service_buyer_plan_change_permission_request_credit_card
* service_buyer_plan_change_permission_none

* service_notification_settings_web_provider
* service_notification_settings_email_provider
* service_notification_settings_web_buyer
* service_notification_settings_email_buyer

Some of them can be updated using 

> PUT  /admin/api/services/{id}.json

But not all of them. 

All of them should be available to read and update from service endpoints.

**Comment by secretsurf** [comment]
Opened in jira here https://issues.jboss.org/browse/THREESCALE-2086
