### ISSUE TITLE
missing check for policy "name"

### ISSUE THREAD

**Issue by mkudlej** [3scale/porta#704]
**What happened**:

There is API for registry custom policy introduced in https://github.com/3scale/porta/pull/593
Name + version should be unique. There is check that version is the same as in schema.
But there is not check that name is the same as in schema.

**What you expected to happen**:

There is check that name is the same as in schema.

**How to reproduce it**:

Call API function with parameter name different than in parameter schema.

3scale deployed by template generated by 3scale Operator.

/kind bug

**Comment by hallelujah** [comment]
The name in the schema is just a title.

Look at https://github.com/3scale/apicast/blob/master/gateway/src/apicast/policy/default_credentials/apicast-policy.json

name is `default_credentials` but `schema.name` is `"Anonymous access"`

Closing.

**Comment by secretsurf** [comment]
mkudlej, is there a reason this wasn't opened in jira? i think it's harder to control everything if we have some bugs opened in github and some in jira. but maybe there's a reason?

**Comment by mkudlej** [comment]
@secretsurf The reason is that I've tested upstream deployment of 3scale. Once we have productized builds, I will use Jira. Do we track upstream issues in Jira?
