### ISSUE TITLE
Intermittent Test failures with Oracle DB 

### ISSUE THREAD

**Issue by gsaslis** [3scale/porta#80]
**What happened**:

Test runs fail due to insufficient memory allocated for OracleDB. 
Build logs show: 

```
Errno::ENOMEM: Cannot allocate memory - fork(2)
```

**What you expected to happen**:

Tests to run against a stable database deployment. 

If tests fail, it should be because of the tests, not the test env. 

**How to reproduce it**:

Rather tricky... but it does seem to happen with most `oracle` builds in Jenkins. 

I do _not_ have steps to consistently reproduce, but just starting the oracle pipeline should get you there sooner or later. 

/kind bug

**Comment by Martouta** [comment]
Can we close this issue @gsaslis ? I think this was already solved, right? 😄

**Comment by gsaslis** [comment]
Yup! Thanks for the reminder.
