### ISSUE TITLE
In the UI, "Overview" is highlighted when "Settings" is active.

### ISSUE THREAD

**Issue by Martouta** [3scale/porta#85]
**What happened**:

In the UI, "Overview" is highlighted when "Settings" of a Service is active.
![image](https://user-images.githubusercontent.com/11318903/46391862-45737000-c6df-11e8-97f9-f7ed2ac169b3.png)

**What you expected to happen**:

Not to be highlighted 😄 

**How to reproduce it**:

Going to the page of settings of a service/api.

**Anything else we need to know?**:

/kind bug

**Comment by Martouta** [comment]
Wait... 🤔 @guicassolato and @thomasmaas... Are you sure this is not the proper behaviour already?

I did `rails server` under the `system` repo, the old one, so not here in `porta` and without these new navigation changes.
![image](https://user-images.githubusercontent.com/11318903/46392221-deef5180-c6e0-11e8-9767-a837bb722519.png)
And this is what I see:
![image](https://user-images.githubusercontent.com/11318903/46392235-f3334e80-c6e0-11e8-88be-6d503e99a642.png)

**Comment by thomasmaas** [comment]
Maybe the bug was already there but it’s not what we want.

**Comment by Martouta** [comment]
Ok, then ignore mode on 😂
