### ISSUE TITLE
CI Builds in containers instead of VMs

### ISSUE THREAD

**Issue by gsaslis** [3scale/porta#93]
**Is your feature request related to a problem? Please describe.**

1. At the moment we use Jenkins for our builds and spin up EC2 instances (VMs) to actually run the builds in. 
2. Within those VMs, we use `docker-compose` to run some containers within which the tests will actually be run. 

This has the following problems:
* it is slower:
  * because of container-in-VM, 
  * but more importantly because VM itself takes MUCH longer to spin up than if we were running directly in container. 
* we are tied to amazon / ec2 (though this is not _that_ a tight coupling)
* we cannot run our builds inside openshift. 

**Describe the solution you would like**

Natively run our tests in (a bunch of) containers, without requiring docker-in-docker / docker-compose, etc. 

Assuming our CI will be able to provision containers, our builds would be much faster (considering they now take ~15 mins and VMs take `minutes` to spin up). 

In addition, that would allow us to move away from Amazon/EC2, to either:
* any public CI that supports containers as workers - circleci,travisci,semaphoreci,gitlab ci, etc.), or 
* our own jenkins on kubernetes/openshift, etc.

**Describe alternatives you have considered**

N/A

**Additional context**

I am volunteering to work on this.   : ))

/kind feature

**Comment by mikz** [comment]
@gsaslis VMs take a few minutes to spin up, but they stay alive for a while. So subsequent builds are faster - without any VM boot time.

The test suite can be executed by directly running `rake integrate`, so there is not much to do.

I don't see what needs to be done here. We already have a container image with all the dependencies.
So it is really just about the CI to decide if it wants to start containers or not and run `rake integrate` directly.

**Comment by gsaslis** [comment]
> @gsaslis VMs take a few minutes to spin up, but they stay alive for a while. So subsequent builds are faster - without any VM boot time.

true, with emphasis on "for a while". They do spin down eventually, and, when they do, new builds that come up will take some time until they start running again. 

Looking more closely at our jenkins for the past couple of weeks, I think this happens more often than not. (people's builds don't always run at the same time... ) meaning our alternative would be to pay for machines to always be ready to run the tests, but to have them sit around doing nothing most of the time (when it happens that we don't have enough tests to run). That's why I think containers will help (the startup time is no longer an issue). 

> So it is really just about the CI to decide if it wants to start containers or not and run rake integrate directly.

Yes, this is what this issue is about. From what I've seen so far, this would only require the `Makefile` to be reworked a little to cover both scenarios (docker-compose for running tests locally - as the external contributors might want to use - and native `rake integrate:parallel_*` for the CI that uses containers as workers   ; )

**Comment by gsaslis** [comment]
closing since we've since moved to circleci (where builds do happen in containers)
