### ISSUE TITLE
Automated Dependency Updates

### ISSUE THREAD

**Issue by gsaslis** [3scale/porta#96]
**Is your feature request related to a problem? Please describe.**

Manually updating of our dependencies is a pain.

**Describe the solution you would like**

Wouldn't it be nice if someone notified us and took the trouble of opening a PR, and tests ran against it, etc. etc.

Bots to the rescue: 
* https://dependabot.com/ or 
* https://depfu.com/ or
* https://www.deppbot.com or 
* https://renovatebot.com

**Describe alternatives you have considered**

N/A

**Additional context**

Already used in https://github.com/3scale/echo-api/

/kind feature

**Comment by gsaslis** [comment]
@macejmic i think you were doing some work on updating dependencies, so this might be interesting to you?

**Comment by Martouta** [comment]
@gsaslis now that we have dependabot, can we close this?

**Comment by gsaslis** [comment]
sure 👍 - nice catch!
